
CC=gcc
FLAGS=-Wall -Wextra -Werror
SRC:=/Users/usomer/Desktop/unittests/c05
INTRA:=/Users/usomer/Desktop/unittests/c05

ex00=$(SRC)/starters/fif_main.c $(INTRA)/ex00/ft_iterative_factorial.c -o $(INTRA)/ex00/fif.out





ft_iterative_factorial: $($(SRC)/fif_main.c) $($(INTRA),/ex00/ft_iterative_factorial.c)
	$(CC) $(FLAGS) $(ex00)

ft_recursive_factorial: $($(SRC)/frf_main.c) $($(INTRA),/ex01/ft_recursive_factorial.c)
	$(CC) $(FLAGS) $($(SRC),/starters/frf_main.c) $($(INTRA),/ex01/ft_recursive_factorial.c -o frf.out)

ft_recursive_power: $($(SRC)/frp_main.c) $($(INTRA),/ex03/ft_recursive_power.c)
	$(CC) $(FLAGS) $($(SRC),/starters/frp_main.c) $($(INTRA),/ex03/ft_recursive_power.c -o frp.out)

ft_iterative_power: $($(SRC)/fio_main.c) $($(INTRA),/ex02/ft_iterative_power.c)
	$(CC) $(FLAGS) $($(SRC),/starters/fio_main.c) $($(INTRA),/ex02/ft_iterative_power.c -o fio.out)

ft_fibonacci: $($(SRC)/ff_main.c) $($(INTRA),/ex04/ft_fibonacci.c)
	$(CC) $(FLAGS) $($(SRC),/starters/ff_main.c) $($(INTRA),/ex04/ft_fibonacci.c -o ff.out)

ft_sqrt: $($(SRC)/fs_main.c) $($(INTRA),/ex05/ft_sqrt.c)
	$(CC) $(FLAGS) $($(SRC),/starters/fs_main.c) $($(INTRA),/ex05/ft_sqrt.c -o fs.out)

ft_is_prime: $($(SRC)/fip_main.c) $($(INTRA),/ex06/ft_is_prime.c)
	$(CC) $(FLAGS) $($(SRC),/starters/fip_main.c) $($(INTRA),/ex06/ft_is_prime.c -o fip.out)

ft_find_next_prime: $($(SRC)/ffnp_main.c) $($(INTRA),/ex07/ft_find_next_prime.c)
	$(CC) $(FLAGS) $($(SRC),/starters/ffnp_main.c) $($(INTRA),/ex07/ft_find_next_prime.c -o ffnp.out)
